# Generated by Django 5.2.9 on 2025-12-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_chat_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram_id"
            ),
        ),
    ]
