# Generated by Django 6.0 on 2025-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="complete_time",
            field=models.IntegerField(verbose_name="Время на выполнение в сек"),
        ),
    ]
