# Generated by Django 5.2.9 on 2025-12-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_habit_complete_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
